#!/usr/bin/bash

set -e

OSTREEINIT="/usr/lib/ostreeinit/ostreeinit"

usage() {
    if test "$#" -ne 0; then
        echo "$@"
        echo
    fi
    echo "Usage: ostreeinit-mkinitrd [OPTION...] FILE"
    echo
    echo " -h --help	Display usage"
    echo " --init=FILE	Specify custom init binary"
}

VALID_ARGS=$(getopt -o h --long help,init: -- "$@")
if [[ $? -ne 0 ]]; then
    exit 1;
fi

eval set -- "$VALID_ARGS"
while [ : ]; do
  case "$1" in
    --init)
        OSTREEINIT="$2"
        shift 2
        ;;
    --) shift;
        break
        ;;
    -h | --help)
        usage
        exit 0
  esac
done

if [ "$#" -lt 1 ]; then
    usage "Missing destination name"
    exit 1
fi

DEST=$1
shift

if test "$#" -ne 0; then
    usage "Unexpected commandline arguments: $@"
    exit 1
fi

BINS=/usr/lib/ostree/ostree-prepare-root

files=()
declare -A filesDict

run_ldd() {
    ldd $1 | grep "=>" | awk "{ print \$3 }"
    ldd $1 | grep -v "=>" | grep ld-linux | awk "{ print \$1 }"
}

add_file() {
    local file=$1
    if [ "${filesDict[$file]}" != 1 ]; then
        add_parents $file
        filesDict[$file]=1
        files+=($file)
    fi
}

add_parents() {
    local p=$(dirname $1)
    while [ "$p" != "/" ]; do
        add_file $p
        p=$(dirname $p)
    done
}

add_binary() {
    local bin=$1
    add_file $bin
    for dep in $(run_ldd $bin); do
        add_file $dep
    done
}


add_file /proc
add_file /sys
add_file /dev
add_file /run

for bin in $BINS; do
    add_binary $bin
done

D=$(mktemp -d)
cp $OSTREEINIT $D/init

echo init  | cpio -D $D  -H newc -o -O $D/initrd
for file in "${files[@]}"; do
    echo $file;
done | cpio -D /  -L -H newc -o -A -O $D/initrd

lz4 -l -9 -c $D/initrd > $DEST

rm -rf $D
